api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        serializer:
            hydra_prefix: true
            
    mapping:
        paths: 
            - '%kernel.project_dir%/src/Authentication/Domain/FeatureRollout'
            - '%kernel.project_dir%/src/Authentication/Domain/Organization'
            - '%kernel.project_dir%/src/Authentication/Domain/User'
            - '%kernel.project_dir%/src/Authentication/Domain/Role'
            - '%kernel.project_dir%/src/Authentication/Domain/Workspace'
