services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\Cloud\Management\:
        resource: '../../../src/Cloud/Management'
        exclude:
            - '../../../src/Cloud/Management/Domain/'
            - '../../../src/Cloud/Management/Infrastructure/CloudProviderAccount/DataFixtures'
            - '../../../src/Cloud/Management/Infrastructure/Datacenter/DataFixtures'
            - '../../../src/Cloud/Management/Infrastructure/Region/DataFixtures'
        
    App\Cloud\Management\Domain\CloudProviderAccount\Query\UseCases\:
        resource: '../../../src/Cloud/Management/Domain/CloudProviderAccount/Query/UseCases/*{Handler}.php'

    App\Cloud\Management\Domain\CloudProviderAccount\Query\CloudProviderAccountRepositoryInterface: '@App\Cloud\Management\Infrastructure\CloudProviderAccount\InMemoryCloudProviderAccountRepository'

    App\Cloud\Management\Infrastructure\CloudProviderAccount\InMemoryCloudProviderAccountRepository:
        factory: [ 'App\Cloud\Management\Infrastructure\CloudProviderAccount\InMemoryCloudProviderAccountRepository', 'buildTestRepository' ]
        arguments:
            $cipher: '@App\Platform\Domain\Vault\Cipher\SodiumSecretBox'
