api_doc:
    path: /docs.{_format}
    methods: ['GET', 'HEAD']
    defaults:
        _controller: 'api_platform.action.documentation'
        _format: ~
        _api_respond: true

#oauth:
#    resource:
#        path: ../src/Authentication/Infrastructure/OAuth
#        namespace: App\Authentication\Infrastructure\OAuth
#    type: attribute
